# Site settings

# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brandon Biggs

email: brandon@brandonbiggs.io

#description: >- # this means to ignore newlines until "baseurl:"
#  My awesome website!

baseurl: "" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site, e.g. http://example.com

#twitter_username: jekyllrb
github_username:  brandonbiggs

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Additions

# Google Analytics - Just add {{ site.google_analytics }} to all pages
google_analytics: >-
  <!-- Global site tag (gtag.js) - Google Analytics -->
   <script async src="https://www.googletagmanager.com/gtag/js?id=UA-135677826-1"></script>
   <script>
     window.dataLayer = window.dataLayer || [];
     function gtag(){dataLayer.push(arguments);}
     gtag('js', new Date());
     gtag('config', 'UA-135677826-1');
   </script>

google_form: >-
  <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfHdGCEgSF4Ozj51bY6GZwJo0XLvoNenVPHVsc-GZa3_-CXYw/viewform?embedded=true" width="640" height="751" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>